-- AlterTable
ALTER TABLE `product` ADD COLUMN `isFlash` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isSpecial` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isWeekly` BOOLEAN NOT NULL DEFAULT false;

